# Generated by Django 5.2.7 on 2025-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=20)),
                ('public_id', models.CharField(max_length=32)),
                ('enclave_key', models.CharField(max_length=32)),
                ('signing_key', models.TextField()),
                ('encryption_key', models.TextField()),
            ],
        ),
    ]
