# Generated by Django 5.2.7 on 2025-11-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theboardmember',
            name='passphrase',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='theboardmember',
            name='private_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='theboardmember',
            name='public_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='enclave_key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='public_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='screen_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
