# Generated by Django 5.2.7 on 2025-11-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0002_theboardmember_passphrase_theboardmember_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theboardmember',
            name='encryption_key',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='signing_key',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
