# Generated by Django 5.2.7 on 2025-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0003_alter_theboardmember_encryption_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theboardmember',
            name='encryption_key',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='signing_key',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
