# Generated by Django 5.2.7 on 2025-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0004_alter_theboardmember_encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theboardmember',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='theboardmember',
            name='public_key',
        ),
        migrations.AddField(
            model_name='theboardmember',
            name='server_signing_key',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
