# Generated by Django 5.2.7 on 2025-11-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0005_remove_theboardmember_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theboardmember',
            name='id',
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='screen_name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
