# Generated by Django 5.2.7 on 2025-11-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0006_remove_theboardmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theboardmember',
            name='passphrase',
            field=models.CharField(default='', max_length=120),
        ),
    ]
