# Generated by Django 5.2.7 on 2025-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0007_alter_theboardmember_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theboardmember',
            name='enclave_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='public_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
