# Generated by Django 5.2.7 on 2025-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0008_alter_theboardmember_enclave_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theboardmember',
            name='enclave_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='theboardmember',
            name='public_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
