# Generated by Django 5.2.7 on 2025-11-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0010_alter_theboardmember_enclave_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionContext',
            fields=[
                ('screen_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64, null=True)),
                ('ephemeral_key', models.CharField(max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
