# Generated by Django 5.2.7 on 2025-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0011_sessioncontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontext',
            name='session_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
