# Generated by Django 5.2.7 on 2025-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboardapi', '0012_sessioncontext_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='theboardmember',
            name='private_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
